services:
  postgres:
    image: postgres:16
    container_name: sp-postgres
    environment:
      POSTGRES_DB: shopping
      POSTGRES_USER: shopping
      POSTGRES_PASSWORD: shopping
    ports:
      - "5433:5432"
    volumes:
      - sp_postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: sp-mongo
    ports:
      - "27017:27017"
    volumes:
      - sp_mongo_data:/data/db

  cassandra:
    image: cassandra:4.1
    container_name: sp-cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "shopping-cluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    volumes:
      - sp_cassandra_data:/var/lib/cassandra

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: sp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: sp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # 让你本机可以用 localhost:9092 连接
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # 单节点需要
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  sp_postgres_data:
  sp_mongo_data:
  sp_cassandra_data: