server:
  port: 9001

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5433/shopping
    username: shopping
    password: shopping
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

services:
  item-service:
    base-url: http://localhost:9002